version: '3'

services:
  coordinator:
    image: "lewuathe/trino-coordinator:327-SNAPSHOT-corretto"
    ports:
      - "8080:8080"
    container_name: "coordinator"
    command: coordinator
  worker0:
    image: "lewuathe/trino-worker:327-SNAPSHOT-corretto"
    container_name: "worker0"
    ports:
      - "8081:8081"
    command: worker0
  worker1:
    image: "lewuathe/trino-worker:327-SNAPSHOT-corretto"
    container_name: "worker1"
    ports:
      - "8082:8081"
    command: worker1
